### ISSUE TITLE
Access Denied: You must use HTTPS

### ISSUE THREAD

**Issue by sebicas** [Mashape/kong-oauth2-hello-world#1]
I keep getting the following error:

``` javascript
{
  "error_description": "You must use HTTPS",
  "error":"access_denied"
}
```

Is there any way to disable SSL for testing in development?

**Comment by sebicas** [comment]
After some research I finally was able to make Chrome accept my self signed certificate.

Here is the link to the article that helped me:
http://www.robpeck.com/2010/10/google-chrome-mac-os-x-and-self-signed-ssl-certificates/#.VhVIahNVhBc

**Comment by sonicaghi** [comment]
@thefosk maybe worth adding this resource in the doc of the plugin or in the example doc?
