### ISSUE TITLE
example problem with kong version 0.11.1 (running in docker ce version 17.09.0-ce-mac35 (19611) on macOS 10.13.1)

### ISSUE THREAD

**Issue by progamer71** [Mashape/kong-oauth2-hello-world#10]
I have followed the example step by step.

It work well until I click the "Authorize" button in browser, kong redirect my browser to http://getkong.org with code like in the example.

http://getkong.org/?code=e3YgIGs1TPJqKYAZJStcjaOCiqfumAfP

next step I will acquire access token with (note: I have changed client_id, client_secret and code to my configuration information)

curl https://127.0.0.1:8443/oauth2/token \
     -H "Host: test.com" \
     -d "grant_type=authorization_code" \
     -d "client_id=li4Th0DMMe28cgTQ1jSP6hsLvQMTiSbf" \
     -d "client_secret=LSVbkvq9943LbVW1NBANCbtgOEGJ3cNV" \
     -d "redirect_uri=http://getkong.org/" \
     -d "code=e3YgIGs1TPJqKYAZJStcjaOCiqfumAfP" --insecure

I expect kong should response access token in json format but I got
{"error_description":"Invalid code","error":"invalid_request"}

I have tried to remove -H "Host: test.com" and I got
curl https://127.0.0.1:8443/oauth2/token \
     -d "grant_type=authorization_code" \
     -d "client_id=li4Th0DMMe28cgTQ1jSP6hsLvQMTiSbf" \
     -d "client_secret=LSVbkvq9943LbVW1NBANCbtgOEGJ3cNV" \
     -d "redirect_uri=http://getkong.org/" \
     -d "code=e3YgIGs1TPJqKYAZJStcjaOCiqfumAfP" --insecure
{"message":"no API found with those values"}

I stuck at this point for 2-3 days. I don't know how to fix it.

Please note that I have successfully configured basic authentication and key authentication but oAuth2 plug-in.

**Comment by mangvlad** [comment]
Looks like this works (note URL has cats in it):

curl https://127.0.0.1:8443/cats/oauth2/token \
      -d "grant_type=authorization_code" \
      -d "client_id=2JxPT4vcH73kXTOUAPRUeFFJfEoWARfN" \
      -d "client_secret=2A8XnH7aldO1TPyl9Xh1MBuy2kNy63DI" \
      -d "redirect_uri=http://getkong.org/" \
      -d "code=q7DhOyGVQX9TowQCtEkcm6vzJm8xXeFQ" --insecure

**Comment by progamer71** [comment]
@mangvlad Thanks you very much. Your solution work.
for people who have same problem as me

You have to remove 
-H "Host: test.com" \
and change 
curl https://127.0.0.1:8443/oauth2/token 
to 
curl https://127.0.0.1:8443/cats/oauth2/token 

you should get something like this
{
  "refresh_token":"0kTQWBirzgO6KTazuCLwQY55A1fBWMXI",
  "token_type":"bearer",
  "access_token":"F8Q4LBmJ8ehI0X2FEJqWkUP3LAxE1Wff",
  "expires_in":7200
}
