### ISSUE TITLE
Does the oauth plugin work with routes (as opposed to apis)?

### ISSUE THREAD

**Issue by arrobeusa** [Mashape/kong-oauth2-hello-world#13]
I've gone through the example using `apis` (and it works), but I can't get it to work with `routes`. For example, I have a service with a `/foo` route. The resulting authorize endpoint is then `/foo/oauth2/authorize` and I get a "no route and no API found with those values" message. I'm guessing I'm using the wrong route because the service works fine when not using the oauth plugin.

**Comment by arrobeusa** [comment]
I figure this out. The `/foo/oauth2/authorize` request is a POST so I had to include POST in the methods for the route. I only had GET initially

**Comment by Tieske** [comment]
Tnx for posting the resolution!
