### ISSUE TITLE
Update for Kong CE 0.14?

### ISSUE THREAD

**Issue by jerneyio** [Mashape/kong-oauth2-hello-world#14]
Any plans to update this for Kong CE 0.14 to use `/services` instead of `/apis`? I've gotten this working myself and would be happy to submit a PR with the changes to the app.js code and README.md

**Comment by Tieske** [comment]
🐒   ❤️  PR

**Comment by jerneyio** [comment]
PR is here: https://github.com/Kong/kong-oauth2-hello-world/pull/15
