### ISSUE TITLE
Plugin problems

### ISSUE THREAD

**Issue by pchlebda** [Mashape/kong-oauth2-hello-world#7]
I run my kong on docker.
After following instructions on https://github.com/Mashape/kong-oauth2-hello-world
I still get {"message":"no API found with those values"} .
The logs in /usr/local/kong/logs don't give much information either.
Could you please advise ?

**Comment by bgouz** [comment]
The problems is likely not with the plugin, but with how yiu configured your APIs. Should be easy to troubleshoot  (please supply the /apis admin endpoint)

**Comment by progamer71** [comment]
@pchlebda you probably have the same problem as me.
Please look at my closed ticket #10.

**Comment by Tieske** [comment]
duplicate of #10. Readme was updated.
